version: "3.8"

services:
  app:
    build: .
    container_name: excel-go-libxls
    # ports:
    #   - "3020:3020"
    restart: always
    # volumes:
    #    # Optional: untuk melihat hasil upload di host
    #   - ./uploads:/root/uploads
