version: "3.8"

services:
  app:
    build: .
    container_name: excel-go-app
    # ports:
    #   - "3020:3020"
    restart: always
    # Opsional: Limits resource agar container tidak memakan semua RAM jika file excel raksasa
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.5'
    #      memory: 512M
